### ISSUE TITLE
Undefined array key "sf_event_mgt_indexer"

### ISSUE THREAD

**Issue by avahle** [derhansen/sf_event_mgt_indexer#18] opened 2022-06-24 09:56 UTC
After executing the indexer following log error messages occur:

Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in xxx/sf_event_mgt_indexer/Classes/Indexer/EventIndexer.php line 98
Core: Error handler (BE): PHP Warning: Undefined array key "sf_event_mgt_indexer" in xxx/sf_event_mgt_indexer/Classes/Indexer/EventIndexer.php line 98
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in xxx/sf_event_mgt_indexer/Classes/Indexer/EventIndexer.php line 90

There are no hooks defined for this extension - therefore the array `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['sf_event_mgt_indexer']` isn't initialized in this case.

The error occurs with TYPO3 11.5 (composer), PHP 8.1, extension version 3.0.0

**Comment by derhansen** [comment] 2022-06-25 12:52
Thanks for your report. The problem is fixed in version 3.0.1

**Closed as completed by derhansen** 2022-06-25 12:52 UTC
